=== clonegod/x01-lang-java/internet_Architec/distributed_services/webservice/src/main/java/com/asynclife/xml/dtd/classroom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classroom (cname,grade,students)>
<!ATTLIST classroom cid ID #REQUIRED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (id,name,age)> <!-- xml中元素书写顺序必须与这里一致 -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== clonegod/x01-lang-java/internet_Architec/distributed_services/webservice/src/main/java/com/asynclife/xml/dtd/classroom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "classroom.dtd">
<classroom cid="c1">
	<cname>班级1</cname>
	<grade>三年级</grade>
	<students>
		<student>
			<id>1</id>
			<name>aa</name>
			<age>10</age>
		</student>
		<student>
			<id>2</id>
			<name>bb</name>
			<age>20</age>
		</student>
	</students>
</classroom>
